### ISSUE TITLE
Kafka output plugin not playing nice with other plugins

### ISSUE THREAD

**Issue by xpajaro** [fujiwara/fluent-agent-hydra#2]
If you place the kafka match config after the stdout config, it doesn't produce any events.
It also does not give any errors or information that lets you know why it's not working. I discovered the fix by dumb luck.

Thanks for such a great plugin, btw.

**Comment by fujiwara** [comment]
Sorry, this repository is for "fluent-agent-hydra", not for "fluent-plugin-kafka".
