### ISSUE TITLE
stay connected to fluentd

### ISSUE THREAD

**Issue by fahimeh2010** [fujiwara/fluent-agent-hydra#24]
Hello
First thank you for your open source project.
Is it possible to set during of connection time to fluentd in hydra?
Because after a while it log "2016/10/03 09:51:46 [info] Connect to foo:10252" and I miss the log at this time?
Thank you

**Comment by fujiwara** [comment]
hydra keeps TCP connection to fluentd, and refreshes the connection after 100 recordSet sent.
https://github.com/fujiwara/fluent-agent-hydra/blob/master/hydra/out_forward.go#L107-L109

**Comment by fahimeh2010** [comment]
is it possible to increase 100 recordSet?and how?

**Comment by fujiwara** [comment]
Currently, `maxKeepAliveSentCount` is a constant.
I'm considering to it be configurable.

**Comment by fahimeh2010** [comment]
Thank you, we will be waiting for it
